config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :reviews
  end
  root to: 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  before_save(:titleize_product)
  validates :name, presence: true
  validates :cost, presence: true
  validates :country, presence: true

  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}
  scope :usa, -> {where(country: "USA")}
  scope :top_review , -> {left_joins(:reviews).group(:id).order('COUNT(reviews.id) DESC').limit(1)}
  # https://stackoverflow.com/questions/16996618/rails-order-by-results-count-of-has-many-association

    private
      def titleize_product
        self.name = self.name.titleize
      end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: (1..5),
    message: "%{value} is not a valid rating, please rate from 1 to 5." }
  validates :content_body, length: { minimum: 50 }
  validates :content_body, length: { maximum: 250 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    params.permit!
    @products = Product.all
    @top_three = Product.three_most_recent
    @usa = Product.usa
    @top_review = Product.top_review
    render :index
  end

  def new
    params.permit!
    @product = Product.new
    render :new
  end

  def create
    params.permit!
    @product = Product.new(params[:product])
    if @product.save
      flash[:notice] = "New Product Added!"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    params.permit!
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    params.permit!
    @product = Product.find(params[:id])
    logger.info @product
    render :show
  end

  def update
    params.permit!
    @product = Product.find(params[:id])
    params.permit!
    if @product.update(params[:product])
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    params.permit!
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(params[:review])
    if @review.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    params.permit!
    @review = Review.find(params[:id])
    if @review.update(params[:review])
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MariosFood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <%= f.submit  %>
<% end %>

app/views/products/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Mario's Special Desserts</h1>
  <p class="lead">Sweet treats from all over the world.</p>
  <hr class="my-4">
  <p>Because ...reasons</p>
</div>
<p><%= link_to "Create new product", new_product_path %></p>
<h3> Top 3 </h3>

<ul>
<% @top_three.each do |p| %>
  <li> <%= link_to p.name, product_path(p)%> </li>
<% end %>
</ul>

<h3> USA Made </h3>

<ul>
<% @usa.each do |p| %>
  <li> <%= link_to p.name, product_path(p)%> </li>
<% end %>
</ul>

<h3> Top Reviewed </h3>

<ul>
<% @top_review.each do |t| %>
  <li> <%= link_to t.name, product_path(t)%> </li>
<% end %>
</ul>

<h3>All Products</h3>
<% if @products.any? %>
<ul>
  <% @products.each do |product| %>
  <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no products yet.</p>
<% end %>

app/views/products/new.html.erb
<h1>Add a new product:</h1>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <p><%= f.submit %></p>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<% if @product.reviews.any? %>
  <h4>Here are the reviews associated with this product:</h4>

  <% @product.reviews.each do |review| %>
    <ul>
      <li><%= link_to (review.author), product_review_path(@product, review) %> (<%= review.rating %>)</li>
    </ul>
  <% end %>
<% else %>
  <p>This product has not been reviewed.</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>
<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/edit.html.erb
<h1>Add a review:</h1>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>

  <p><%= f.submit %></p>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a review:</h1>
<% if @review.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @review.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>

  <p><%= f.submit %></p>
<% end %>

app/views/reviews/show.html.erb
<h1>Author: <%= @review.author %></h1>
<h2>Rating <%= @review.rating %></h2>

<h4>Review: <%= @review.content_body %></h4>

<p><%= link_to "Edit", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete", product_review_path(@product, @review),
                         :data => {:confirm => "Are you sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to product", product_path(@product) %></p>